line-length = 100
target-version = "py311"
select = ["E", "F", "I", "UP", "B"]  # pyflakes/pycodestyle/imports/pyupgrade/bugbear
ignore = ["E501"]                    # don’t fail on long lines (Black handles wrapping)
