name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    env:
      HF_HOME: ${{ github.workspace }}/.hf_cache

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Cache HuggingFace
        uses: actions/cache@v4
        with:
          path: ${{ env.HF_HOME }}
          key: hf-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            hf-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"
          pip install pytest requests httpx fastapi uvicorn
          pip install sentence-transformers
          pip install langchain langchain-community langchain-chroma chromadb
          pip install langchain-huggingface

      - name: Prefetch embedding model (best-effort)
        if: runner.os == 'Linux'
        run: |
          python -c "
          from sentence_transformers import SentenceTransformer
          try:
              model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
              print('Prefetch OK')
          except Exception as e:
              print('Prefetch warning:', e)
          "

      - name: Create directories
        run: |
          mkdir -p data storage

      - name: Ingest demo corpus
        run: python -m rag_assistant.ingest

      - name: Run tests
        run: pytest -q



