name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LLM_PREFERENCE: "none"
      DATA_DIR: "./data"
      CHROMA_DIR: "./storage"
      HF_HOME: ~/.cache/huggingface
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: hf-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            hf-${{ runner.os }}-
      - name: Install project
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -e .
      - name: Pre-create storage dir (idempotent)
        run: mkdir -p ./storage
      - name: Ingest tiny corpus
        run: python -m rag_assistant.ingest
      - name: Run tests
        run: pytest -q
