name: CI

on:
  push:
  pull_request:

env:
  HF_HOME: ${{ runner.temp }}/.cache/huggingface

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Cache HuggingFace
        uses: actions/cache@v4
        with:
          path: ${{ env.HF_HOME }}
          key: hf-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            hf-${{ runner.os }}-

      - name: Install project (editable) + dev
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"

      - name: Prefetch embedding model (sentence-transformers/all-MiniLM-L6-v2)
        run: |
          python - << 'PY'
          from sentence_transformers import SentenceTransformer
          SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
          PY

      - name: Run tests
        run: pytest -q

