name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11"]

    # Simple, portable cache location
    env:
      HF_HOME: ${{ github.workspace }}/.hf_cache

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Cache HuggingFace
        uses: actions/cache@v4
        with:
          path: ${{ env.HF_HOME }}
          key: hf-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            hf-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          # Try dev extras first; fall back to base install
          pip install -e ".[dev]" || pip install -e .
          # Ensure API-test deps are present
          pip install fastapi uvicorn pytest requests httpx sentence-transformers


      - name: Prefetch embedding model (portable)
        run: >
          python -c "from sentence_transformers import SentenceTransformer;
          SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2');
          print('Prefetch OK')"

      - name: Run tests
        run: pytest -q



