name: Dependency Audit
on: [push, pull_request]
jobs:
  audit:
    runs-on: ubuntu-latest
    continue-on-error: true    # ← soft-fail
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pip-audit
        run: |
          python -m pip install -U pip
          pip install pip-audit
      - name: Run pip-audit (report only)
        run: pip-audit || true  # ← don't fail the job yet
